kind: Deployment
apiVersion: apps/v1
metadata:
  name: ethan-b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ethan-b
  template:
    metadata:
      labels:
        app: ethan-b
    spec:
      containers:
        - name: ethan-b
          image: duyhabui/ethan-b
          ports:
            - containerPort: 80
