name: Deploy ethan-b

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '21.7.1'
        - run: npm ci
        - run: npm run build --if-present
        - run: npm test


      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{secrets.GOOGLE_PROJECT}}
          service_account_key: ${{secrets.GOOGLE_APPLICATION_GITHUB_CREDENTIALS}}
          export_default_credentials: true

      - name: build and push the docker image
        env:
          GOOGLE_PROJECT: ${{secrets.GOOGLE_PROJECT}}
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev
          docker build -t europe-west1-docker.pkg.dev/$GOOGLE_PROJECT/react .
          docker push europe-west1-docker.pkg.dev/$GOOGLE_PROJECT/react
